### ISSUE TITLE
Impostors are not mantaining the original form of the multimesh instance

### ISSUE THREAD

**Issue by lucasthomaz97** [zhangjt93/godot-imposter#11]
![image](https://github.com/user-attachments/assets/25bcd066-ff80-423e-9381-4169c8290694)
I was making the impostor for this pine tree i'm implementing in my game, and when i was going to bake the impostor, it was getting every mesh like it's one ahead of another instead of following the position that the quads are disposed in the scene.
These are a multimesh instance with 32 instances of a billboard quadmesh that uses a shader with alpha textures and alpha scissors.

**Comment by zhangjt93** [comment]
Hey there! Mind sharing an example? You can either drop a link here or send it over to [zzjjtt93@163.com](mailto:zzjjtt93@163.com)

**Comment by lucasthomaz97** [comment]
it's pretty simple to reproduce:

in an empty 3d scene add a multimesh instance
add a quadmesh to your scene, in this mesh add a shader with alpha scissors shader and alpha texture, this will be the origin mesh you'll use to populate the multimesh instance
add another mesh instance, it must be like a sphere, a cube, a cylinder, a cone, any shape that has depth and resembles a little of a low poly tree top and set the visibility off to this mesh instance, it will only exist as the surface that delimits the multimesh population and won't be visible in the final result.
click populate on the multimesh instance to open the populate options menu
In the menu choose the surface choose the mesh instance
As the scale, set to a big value, but only a size enough to fill the entire surface of the mesh you toggled invisible
as the instance count, i use 32.
generate.
try to generate an imposter for the multimesh instance
by following this steps you must see the same problem

apparently, it's getting only one of the instances of the multimesh to generate the impostor, or one ahead of the other instead of using the original positions

visible_instance_count set to 1
![image](https://github.com/user-attachments/assets/c2262e2f-2f9d-4358-9008-b0a1665f330b)

the full multimesh instance:
![image](https://github.com/user-attachments/assets/01ddc643-8290-4ead-af21-b6507f3529c8)

now compare the format of the original tree bush to the impostor preview:
![image](https://github.com/user-attachments/assets/77cede29-0928-44bf-9b37-985343311f72)

here is the imposter preview with the visible_instance_count set to 1
![image](https://github.com/user-attachments/assets/06907894-7acc-4561-81f7-1efdd5f0ad63)

**Comment by zhangjt93** [comment]
Yeah, I mean would you mind sharing your model file so I could test it out? I've been pretty swamped lately and haven't had much time to deal with this stuff.

**Comment by lucasthomaz97** [comment]
https://github.com/lucasthomaz97/imposter_multimesh_issue
here is the minimal reproduction project, just install the addon and open the tree.tscn
it's all made in godot with custom shaders and stuff, so i can't just send you a single file, because it's not going to work.

**Comment by zhangjt93** [comment]
Yeah, I think I know what's causing this. I actually just replied to another user who had the exact same issue as you.
#10
