### ISSUE TITLE
Port 3.5?

### ISSUE THREAD

**Issue by AlexeyPe** [zhangjt93/godot-imposter#4]
Port to 3.5?🙏

**Comment by zhangjt93** [comment]
Hey, I suggest you check out this project. 

https://github.com/wojtekpil/Godot-Octahedral-Impostors

I've learned from it and even provided a link to it in the documentation of my project. 

It runs on Godot 3.x, and you can search for "Octahedral Impostors" in AssetLib of version 3.5 to find it.
