### ISSUE TITLE
Issue with impostor generation

### ISSUE THREAD

**Issue by homexhome** [zhangjt93/godot-imposter#7]
Can you help me understand why is this happening? 
I think on the base impostor generation it cuts my prop on the top - what happens next is on the last screenshot. Maybe i don't understand how to properly use your addon, can you help me please?
![Screenshot 2024-01-30 132548](https://github.com/zhangjt93/godot-imposter/assets/105355405/8407750c-41a3-4a5c-9da4-6dab7d79bd84)

https://github.com/zhangjt93/godot-imposter/assets/105355405/190307af-83a4-4715-9fe2-e83b1a649aac

**Comment by homexhome** [comment]
![image](https://github.com/zhangjt93/godot-imposter/assets/105355405/4e14c7e3-6065-4d50-a05e-9d76c838ff81)

**Comment by zhangjt93** [comment]
I suspect there might be some confusion when calculating the AABB center point of the model. Would you mind sending me your model to my email (zzjjtt93@hotmail.com)? I need to test it out.

**Comment by homexhome** [comment]
Sorry, lost access to this model, if i will encounter any same bugs i will report on it.

**Comment by zhangjt93** [comment]
During my development, I've also encountered similar issues, but based on my testing, I've already resolved them.  So, I suspect that there might be some overlooked aspects in the structure of the object you want to bake, resulting in the confusion of calculating the center point of the AABB.
